study_prefix = "suicide_icd10"

[file_config]
file_names = [
    "define_age.sql",
    "define_note.sql",
    "define_dx_attempt.sql",
    "define_dx_attempt_snomed.sql",
    "define_dx_ideation.sql",
    "define_dx_self_harm.sql",
    "define_dx.sql",
    "define_study_period.sql",
    "table_study_period.sql",
    "table_dx.sql",
    "table_prevalence.sql",
    "version.sql",
    "counts.py"
]
[export_config]
count_list = [
    "suicide_icd10__count_dx_month",
    "suicide_icd10__count_study_period_month",
    "suicide_icd10__meta_version",    
]
